//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Assets {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EasySave.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        //RESX
        
        //--- MainWindow ---
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture); 
            }
        }
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture); 
            }
        }
        
        // --- BackupView ---
        public static string CreateBackup {
            get {
                return ResourceManager.GetString("CreateBackup", resourceCulture); 
            }
        }
        public static string DeleteBackup {
            get {
                return ResourceManager.GetString("DeleteBackup", resourceCulture); 
            }
        }
        public static string EditBackup {
            get {
                return ResourceManager.GetString("EditBackup", resourceCulture); 
            }
        }
        public static string ExecuteBackup {
            get {
                return ResourceManager.GetString("ExecuteBackup", resourceCulture); 
            }
        }
        public static string PauseBackup {
            get {
                return ResourceManager.GetString("PauseBackup", resourceCulture); 
            }
        }
        public static string ResumeBackup {
            get {
                return ResourceManager.GetString("ResumeBackup", resourceCulture); 
            }
        }
        public static string StopBackup {
            get {
                return ResourceManager.GetString("StopBackup", resourceCulture); 
            }
        }
        public static string BackupName {
            get {
                return ResourceManager.GetString("BackupName", resourceCulture); 
            }
        }
        public static string SourceDirectory {
            get {
                return ResourceManager.GetString("SourceDirectory", resourceCulture); 
            }
        }
        public static string TargetDirectory {
            get {
                return ResourceManager.GetString("TargetDirectory", resourceCulture); 
            }
        }
        public static string CompleteType {
            get {
                return ResourceManager.GetString("CompleteType", resourceCulture); 
            }
        }
        public static string DifferentialType {
            get {
                return ResourceManager.GetString("DifferentialType", resourceCulture); 
            }
        }

        public static string BackupType {
            get {
                return ResourceManager.GetString("BackupType", resourceCulture); 
            }
        }
        public static string BrowseFolders {
            get {
                return ResourceManager.GetString("BrowseFolders", resourceCulture); 
            }
        }
        
        // --- SettingsView ---
        public static string ApplyChanges {
            get {
                return ResourceManager.GetString("ApplyChanges", resourceCulture); 
            }
        }
        public static string BuisnessSoftware {
            get {
                return ResourceManager.GetString("BuisnessSoftware", resourceCulture); 
            }
        }
        public static string EncryptedExtensions {
            get {
                return ResourceManager.GetString("EncryptedExtensions", resourceCulture); 
            }
        }
        public static string FileMaxSize {
            get {
                return ResourceManager.GetString("FileMaxSize", resourceCulture); 
            }
        }
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture); 
            }
        }
        public static string LogFileDirectory {
            get {
                return ResourceManager.GetString("LogFileDirectory", resourceCulture); 
            }
        }
        public static string LogFileFormat {
            get {
                return ResourceManager.GetString("LogFileFormat", resourceCulture); 
            }
        }
        public static string PrioritizedExtensions {
            get {
                return ResourceManager.GetString("PrioritizedExtensions", resourceCulture); 
            }
        }
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture); 
            }
        }
        public static string StateFileDirectory {
            get {
                return ResourceManager.GetString("StateFileDirectory", resourceCulture); 
            }
        }
        
        // --- SettingsView ---
        
        public static string SelectFileOrFolder {
            get {
                return ResourceManager.GetString("SelectFileOrFolder", resourceCulture); 
            }
        }
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture); 
            }
        }
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture); 
            }
        }
    }
}
